spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: CityVista@1104
    
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      
server:
  port: 8080
  
#Eureka
eureka:
  client: 
   serviceUrl:
    defaultZone: http://localhost:8761/eureka/
    
#task-service:
   #ribbon: 
   #listOfServers: http://localhost:8083/,http://localhost:8085/,http://localhost:8086/